import React, { useEffect, useMemo, useState } from "react";
import { api } from "../services/api";
import { formatDate } from "../utils/formatters";
import { statusClass } from "../utils/permissions";

const periods = [["day", "1 Day"], ["week", "1 Week"], ["month", "1 Month"], ["custom", "Custom"]];
const metrics = [["all", "Requests", "totalRequests"], ["approved", "Approved", "approvedRequests"], ["pending", "Pending", "pendingRequests"], ["successful", "Successful", "successfulRequests"]];

export default function ReportsPage({ reports, user }) {
  const [type, setType] = useState("requests"); const [materialType, setMaterialType] = useState("sold"); const [periodKey, setPeriodKey] = useState("week"); const [detail, setDetail] = useState("all");
  const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [custom, setCustom] = useState(null);
  useEffect(() => { if (periodKey === "custom" && start && end) api.reports(user, { start, end }).then(setCustom).catch(() => setCustom(null)); }, [user, periodKey, start, end]);
  const data = periodKey === "custom" ? custom : reports;
  const period = type === "requests" ? data?.periods?.[periodKey] : data?.materialPeriods?.[materialType]?.[periodKey];
  const rows = useMemo(() => { const source = type === "requests" ? period?.requests || [] : period?.materials || []; return type === "requests" && detail !== "all" ? source.filter((row) => row[detail]) : source; }, [type, period, detail]);
  if (!reports) return <div className="panel empty">Loading reports...</div>;
  return <>
    <div className="topbar"><div className="page-title"><h1>Reports</h1><p>Workflow requests, onboarding sales, and general-maintenance leases.</p></div></div>
    <div className="report-tabs"><button className={type === "requests" ? "active" : ""} type="button" onClick={() => setType("requests")}>Request Report</button><button className={type === "materials" && materialType === "sold" ? "active" : ""} type="button" onClick={() => { setType("materials"); setMaterialType("sold"); }}>Materials Sold to Client</button><button className={type === "materials" && materialType === "leased" ? "active" : ""} type="button" onClick={() => { setType("materials"); setMaterialType("leased"); }}>Materials Leased</button></div>
    <div className="report-tabs">{periods.map(([key, label]) => <button className={periodKey === key ? "active" : ""} key={key} type="button" onClick={() => { setPeriodKey(key); setDetail("all"); }}>{label}</button>)}</div>
    {periodKey === "custom" && <section className="panel form-grid two"><label>From<input type="date" value={start} onChange={(e) => setStart(e.target.value)} /></label><label>To<input type="date" min={start} value={end} onChange={(e) => setEnd(e.target.value)} /></label>{(!start || !end) && <small className="field-help">Choose both dates to load the custom timeline.</small>}</section>}
    {type === "requests" ? <section className="stats report-stats report-metrics">{metrics.map(([key, label, value]) => <button className={detail === key ? "stat active" : "stat"} key={key} type="button" onClick={() => setDetail(key)}><span>{label}</span><b>{period?.[value] || 0}</b></button>)}</section> : <section className="stats report-stats report-metrics"><div className="stat"><span>Material Lines</span><b>{period?.totalMaterials || 0}</b></div><div className="stat"><span>Total Quantity {materialType === "sold" ? "Sold" : "Leased"}</span><b>{period?.totalIssued || 0}</b></div></section>}
    <section className="panel"><div className="section-title"><h2>{type === "requests" ? metrics.find(([key]) => key === detail)?.[1] : materialType === "sold" ? "Materials Sold to Client (Onboarding)" : "Materials Leased (General Maintenance)"} / {periods.find(([key]) => key === periodKey)?.[1]}</h2><span>{rows.length} record{rows.length === 1 ? "" : "s"}</span></div>{type === "requests" ? <RequestTable rows={rows} mode={detail} /> : <MaterialTable rows={rows} materialType={materialType} />}</section>
  </>;
}
function RequestTable({ rows, mode }) { if (!rows.length) return <div className="empty">No requests match this report view.</div>; return <div className="table-wrap reports-table-wrap"><table className="reports-table"><thead><tr><th>Number</th><th>Type</th><th>Client</th><th>Status</th><th>Department</th><th>Created</th><th>Reason</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.number}</strong></td><td>{row.type === "doc1" ? "Onboarding & Stock" : "General Maintenance"}</td><td>{row.clientName}<br /><small>{row.location}</small></td><td><span className={`status ${statusClass(row.status)}`}>{row.status}</span></td><td>{row.currentDepartment}</td><td>{formatDate(row.createdAt)}</td><td>{reason(row, mode)}</td></tr>)}</tbody></table></div>; }
function MaterialTable({ rows, materialType }) { if (!rows.length) return <div className="empty">No materials have been {materialType === "sold" ? "sold" : "leased"} in this period.</div>; return <div className="table-wrap reports-table-wrap"><table className="reports-table"><thead><tr><th>Requisition</th><th>Client</th><th>Item ID</th><th>Material</th><th>Purpose</th><th>{materialType === "sold" ? "Sold Qty" : "Leased Qty"}</th><th>{materialType === "sold" ? "Sold" : "Leased"}</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><strong>{row.number}</strong></td><td>{row.clientName}<br /><small>{row.location}</small></td><td>{row.itemId}</td><td>{row.name}</td><td>{row.purpose}</td><td>{row.issuedQty}</td><td>{formatDate(row.issuedAt)}</td></tr>)}</tbody></table></div>; }
function reason(row, mode) { if (mode === "pending" || row.pending) return row.pendingReason || "-"; if (mode === "successful" || row.successful) return "Workflow completed successfully."; if (mode === "approved" || row.approved) return row.successful ? "Final approval completed." : "Approved and waiting for the next workflow step."; return row.rejectionReason || row.pendingReason || "-"; }
