export const emptyItem = {
  itemId: "",
  name: "",
  requestedQty: 1,
  issuedQty: 0,
  serialNumber: "",
  purpose: "",
  unitCost: 0,
};

export const engineerStockItems = [
  { id: "ITM-019", description: "D Link Switch 16 Port", unitCost: 69 },
  { id: "ITM-020", description: "D Link Switch 24 Ports", unitCost: 0 },
  { id: "ITM-021", description: "D Link Switch 8 Ports", unitCost: 18 },
  { id: "ITM-022", description: "Extension Plugs", unitCost: 20 },
  { id: "ITM-023", description: "EnGenius (INT)/ ENGENIUS FIT WI-FI 6", unitCost: 116 },
  { id: "ITM-024", description: "EnGenius 2.4GHz+5GHz 11ac/b/g/n Dual", unitCost: 140 },
  { id: "ITM-025", description: "EnGenius FIT Series Management", unitCost: 134 },
  { id: "ITM-026", description: "EnGenius (INT) PRODUCT LFP", unitCost: 370 },
  { id: "ITM-027", description: "EnGenius (INT) PRODUCT 1102A1359300", unitCost: 134 },
  { id: "ITM-028", description: "Face Plate Modules -Double", unitCost: 8 },
  { id: "ITM-029", description: "Fate Modules - Single", unitCost: 5 },
  { id: "ITM-030", description: "FTP Cable (Roll)", unitCost: 269 },
  { id: "ITM-031", description: "FTTx-OSD-C SC/PC 4 core inclu", unitCost: 14 },
  { id: "ITM-032", description: "Inverter 3K-5KVA/ 48VDC", unitCost: 0 },
  { id: "ITM-033", description: "Invertor SK 1100VA 12V", unitCost: 0 },
  { id: "ITM-034", description: "Linksys Wireless Router", unitCost: 57 },
  { id: "ITM-035", description: "Mikrotik 2011", unitCost: 132 },
  { id: "ITM-036", description: "Mikrotik Billing Router RB 750", unitCost: 86 },
  { id: "ITM-037", description: "Mikrotik Billing Router RB 952UI", unitCost: 71 },
  { id: "ITM-038", description: "Mikrotik Router 1100", unitCost: 374 },
  { id: "ITM-039", description: "MIMO OMNI WI-FI ANTENNAE (UBIQ", unitCost: 319 },
  { id: "ITM-040", description: "Media convertor 1G", unitCost: 57 },
  { id: "ITM-041", description: "Media convertor 10/100", unitCost: 18 },
  { id: "ITM-042", description: "NANO STATION M2", unitCost: 108 },
  { id: "ITM-043", description: "NANO STATION M5", unitCost: 96 },
  { id: "ITM-044", description: "ODF Patch panel 48C fiber", unitCost: 0 },
  { id: "ITM-045", description: "ONU Adaptor", unitCost: 12 },
  { id: "ITM-046", description: "Panel 12 Ports", unitCost: 0 },
  { id: "ITM-047", description: "Patch Panel 24 Ports Fiber", unitCost: 0 },
  { id: "ITM-048", description: "Patch panel 48 Ports Fiber", unitCost: 0 },
  { id: "ITM-049", description: "Panel Cat 6", unitCost: 0 },
  { id: "ITM-050", description: "Pipe 1 & 1/2\"", unitCost: 40 },
];

export const defaultPricing = {
  usdToTzsRate: 2500,
  items: engineerStockItems.map(({ id, description, unitCost }) => ({ id, description, unitCostUsd: unitCost })),
};

export const serviceTypes = [
  ["new_installation", "New Installation"],
  ["reconnection", "Reconnection"],
  ["wifi_extension", "WiFi Extension"],
  ["shifting_connection", "Shifting Connection"],
  ["general_maintenance", "General Maintenance"],
];

export const requestedServices = [
  "Dedicated Internet",
  "Broadband Internet",
  "Fibre Internet",
  "WiFi Installation",
  "Network Installation",
  "Link Maintenance",
];

export const subscriptionPackages = [
  "Home 10 Mbps",
  "Home 20 Mbps",
  "Business 20 Mbps",
  "Business 50 Mbps",
  "Business 100 Mbps",
  "Dedicated 10 Mbps",
  "Dedicated 20 Mbps",
  "Dedicated 50 Mbps",
  "Dedicated 100 Mbps",
];

export const currencies = ["TZS", "USD"];

export const locationOptions = [
  { name: "Mkunazini", area: "Stone Town" },
  { name: "Darajani", area: "Stone Town" },
  { name: "Kiponda", area: "Stone Town" },
  { name: "Malindi", area: "Stone Town" },
  { name: "Forodhani", area: "Stone Town" },
  { name: "Shangani", area: "Stone Town" },
  { name: "Vuga", area: "Stone Town" },
  { name: "Mchangani", area: "Stone Town" },
  { name: "Mlandege", area: "Zanzibar City" },
  { name: "Michenzani", area: "Zanzibar City" },
  { name: "Kikwajuni", area: "Zanzibar City" },
  { name: "Kilimani", area: "Zanzibar City" },
  { name: "Amani", area: "Zanzibar City" },
  { name: "Kwa Mchina", area: "Zanzibar City" },
  { name: "Mwanakwerekwe", area: "Zanzibar City" },
  { name: "Magomeni", area: "Zanzibar City" },
  { name: "Kisauni", area: "Zanzibar West" },
  { name: "Mbweni", area: "Zanzibar West" },
  { name: "Chukwani", area: "Zanzibar West" },
  { name: "Mazizini", area: "Zanzibar West" },
  { name: "Kiembesamaki", area: "Zanzibar West" },
  { name: "Fuoni", area: "Zanzibar West" },
  { name: "Bububu", area: "Zanzibar West" },
  { name: "Mtoni", area: "Zanzibar West" },
  { name: "Chuini", area: "Zanzibar West" },
  { name: "Kiembe Samaki Airport", area: "Airport" },
  { name: "Abeid Amani Karume International Airport", area: "Airport" },
  { name: "Nungwi", area: "North Zanzibar" },
  { name: "Kendwa", area: "North Zanzibar" },
  { name: "Kiwengwa", area: "North-East Zanzibar" },
  { name: "Matemwe", area: "North-East Zanzibar" },
  { name: "Paje", area: "South-East Zanzibar" },
  { name: "Jambiani", area: "South-East Zanzibar" },
  { name: "Bwejuu", area: "South-East Zanzibar" },
  { name: "Makunduchi", area: "South Zanzibar" },
  { name: "Kizimkazi", area: "South Zanzibar" },
  { name: "Fumba", area: "South-West Zanzibar" },
];
