export const emptyItem = {
  itemId: "",
  name: "",
  requestedQty: 1,
  issuedQty: 0,
  serialNumber: "",
  purpose: "",
  unitCost: 0,
};

export const engineerStockItems = [
  { id: "NET-001", description: "UTP Network Cable CAT6" },
  { id: "FIB-001", description: "Fibre Optic Drop Cable" },
  { id: "RTR-001", description: "Network Router" },
  { id: "RAD-001", description: "Outdoor Radio" },
  { id: "SWT-001", description: "Network Switch" },
  { id: "ONT-001", description: "Optical Network Terminal (ONT)" },
  { id: "AP-001", description: "Wireless Access Point" },
  { id: "POE-001", description: "PoE Injector" },
  { id: "SFP-001", description: "SFP Transceiver Module" },
  { id: "PAT-001", description: "CAT6 Patch Cord" },
  { id: "FPC-001", description: "Fibre Patch Cord" },
  { id: "ODF-001", description: "Optical Distribution Frame" },
  { id: "RCK-001", description: "Network Rack" },
  { id: "UPS-001", description: "Uninterruptible Power Supply (UPS)" },
  { id: "CON-001", description: "RJ45 Connector" },
  { id: "SPL-001", description: "Fibre Optic Splitter" },
  { id: "SLV-001", description: "Fusion Protection Sleeve 60mm" },
];

export const serviceTypes = [
  ["new_installation", "New Installation"],
  ["reconnection", "Reconnection"],
  ["wifi_extension", "WiFi Extension"],
  ["shifting_connection", "Shifting Connection"],
  ["general_maintenance", "General Maintenance"],
];

export const requestedServices = [
  "Dedicated Internet",
  "Broadband Internet",
  "Fibre Internet",
  "WiFi Installation",
  "Network Installation",
  "Link Maintenance",
];

export const subscriptionPackages = [
  "Home 10 Mbps",
  "Home 20 Mbps",
  "Business 20 Mbps",
  "Business 50 Mbps",
  "Business 100 Mbps",
  "Dedicated 10 Mbps",
  "Dedicated 20 Mbps",
  "Dedicated 50 Mbps",
  "Dedicated 100 Mbps",
];

export const currencies = ["TZS", "USD"];

export const locationOptions = [
  { name: "Mkunazini", area: "Stone Town" },
  { name: "Darajani", area: "Stone Town" },
  { name: "Kiponda", area: "Stone Town" },
  { name: "Malindi", area: "Stone Town" },
  { name: "Forodhani", area: "Stone Town" },
  { name: "Shangani", area: "Stone Town" },
  { name: "Vuga", area: "Stone Town" },
  { name: "Mchangani", area: "Stone Town" },
  { name: "Mlandege", area: "Zanzibar City" },
  { name: "Michenzani", area: "Zanzibar City" },
  { name: "Kikwajuni", area: "Zanzibar City" },
  { name: "Kilimani", area: "Zanzibar City" },
  { name: "Amani", area: "Zanzibar City" },
  { name: "Kwa Mchina", area: "Zanzibar City" },
  { name: "Mwanakwerekwe", area: "Zanzibar City" },
  { name: "Magomeni", area: "Zanzibar City" },
  { name: "Kisauni", area: "Zanzibar West" },
  { name: "Mbweni", area: "Zanzibar West" },
  { name: "Chukwani", area: "Zanzibar West" },
  { name: "Mazizini", area: "Zanzibar West" },
  { name: "Kiembesamaki", area: "Zanzibar West" },
  { name: "Fuoni", area: "Zanzibar West" },
  { name: "Bububu", area: "Zanzibar West" },
  { name: "Mtoni", area: "Zanzibar West" },
  { name: "Chuini", area: "Zanzibar West" },
  { name: "Kiembe Samaki Airport", area: "Airport" },
  { name: "Abeid Amani Karume International Airport", area: "Airport" },
  { name: "Nungwi", area: "North Zanzibar" },
  { name: "Kendwa", area: "North Zanzibar" },
  { name: "Kiwengwa", area: "North-East Zanzibar" },
  { name: "Matemwe", area: "North-East Zanzibar" },
  { name: "Paje", area: "South-East Zanzibar" },
  { name: "Jambiani", area: "South-East Zanzibar" },
  { name: "Bwejuu", area: "South-East Zanzibar" },
  { name: "Makunduchi", area: "South Zanzibar" },
  { name: "Kizimkazi", area: "South Zanzibar" },
  { name: "Fumba", area: "South-West Zanzibar" },
];
