export const emptyItem = {
  itemId: "",
  name: "",
  requestedQty: 1,
  issuedQty: 0,
  serialNumber: "",
  purpose: "",
  unitCost: 0,
};

export const engineerStockItems = [
  { id: "ITM-001", description: "1GE ONU 862UB - 8653 FGSW/U", unitCost: 46 },
  { id: "ITM-002", description: "24V Adaptor", unitCost: 24 },
  { id: "ITM-003", description: "48V ADAPTOR", unitCost: 31 },
  { id: "ITM-004", description: "4F ADSS FIBER OPTIC CABLE", unitCost: 0 },
  { id: "ITM-005", description: "A86 Socket SC/APC with pigtail", unitCost: 6 },
  { id: "ITM-006", description: "Cabinet 32U", unitCost: 0 },
  { id: "ITM-007", description: "Cabinet 42U", unitCost: 0 },
  { id: "ITM-008", description: "Cabinet 4U", unitCost: 71 },
  { id: "ITM-009", description: "Cabinet 6U", unitCost: 0 },
  { id: "ITM-010", description: "Cabinet 22U-4 FAN", unitCost: 0 },
  { id: "ITM-011", description: "Cabinet 22U-2 FAN", unitCost: 0 },
  { id: "ITM-012", description: "Cabinet 9U", unitCost: 0 },
  { id: "ITM-013", description: "Canopy Power Adaptor", unitCost: 21 },
  { id: "ITM-014", description: "CISCO AP", unitCost: 0 },
  { id: "ITM-015", description: "Cisco Router", unitCost: 0 },
  { id: "ITM-016", description: "Cisco Switch 24 Port", unitCost: 0 },
  { id: "ITM-017", description: "Conduit Pipe - 19mm", unitCost: 1 },
  { id: "ITM-018", description: "Conduit pipe - white (20mm)", unitCost: 2 },
  { id: "ITM-019", description: "D Link Switch 16 Port", unitCost: 69 },
  { id: "ITM-020", description: "D Link Switch 24 Ports", unitCost: 0 },
  { id: "ITM-021", description: "D Link Switch 8 Ports", unitCost: 20 },
  { id: "ITM-022", description: "Extension Plugs", unitCost: 20 },
  { id: "ITM-023", description: "EnGenius (INT) / ENGENIUS FIT WI-FI 6", unitCost: 116 },
  { id: "ITM-024", description: "EnGenius 2.4GHz+5GHz 11ac/b/g/n Dual", unitCost: 140 },
  { id: "ITM-025", description: "EnGenius FIT Series Management", unitCost: 134 },
  { id: "ITM-026", description: "EnGenius (INT) PRODUCT LFP", unitCost: 370 },
  { id: "ITM-027", description: "EnGenius (INT) PRODUCT 1102A1359300", unitCost: 134 },
  { id: "ITM-028", description: "Face Plate Modules -Double", unitCost: 8 },
  { id: "ITM-029", description: "Face Plate Modules - Single", unitCost: 5 },
  { id: "ITM-030", description: "FTP Cable (Roll)", unitCost: 269 },
  { id: "ITM-031", description: "FTTx-OSD-C SC/PC 4 core inclu", unitCost: 28 },
  { id: "ITM-032", description: "Invertor 3.5KVA/ 48VDC", unitCost: 0 },
  { id: "ITM-033", description: "Invertor SK 1100VA 12V", unitCost: 0 },
  { id: "ITM-034", description: "Linksys Wireless Router", unitCost: 57 },
  { id: "ITM-035", description: "Mikrotik 2011", unitCost: 132 },
  { id: "ITM-036", description: "Mikrotik Billing Router RB 750", unitCost: 86 },
  { id: "ITM-037", description: "Mikrotik Billing Router RB 952UI", unitCost: 79 },
  { id: "ITM-038", description: "Mikrotik Router 1100", unitCost: 380 },
  { id: "ITM-039", description: "MIMO OMNI WI-FI ANTENNAE (UBIQ", unitCost: 317 },
  { id: "ITM-040", description: "Media convertor 1G", unitCost: 57 },
  { id: "ITM-041", description: "Media convertor 10/100", unitCost: 18 },
  { id: "ITM-042", description: "NANO STATION M2", unitCost: 108 },
  { id: "ITM-043", description: "NANO STATION M5", unitCost: 96 },
  { id: "ITM-044", description: "ODF Patch panel 48C fiber", unitCost: 0 },
  { id: "ITM-045", description: "ONU Adaptor", unitCost: 13 },
  { id: "ITM-046", description: "Patch Panel 12 Ports", unitCost: 0 },
  { id: "ITM-047", description: "Patch Panel 24 Ports Fiber", unitCost: 0 },
  { id: "ITM-048", description: "Patch panel 48 Ports Fiber", unitCost: 0 },
  { id: "ITM-049", description: "Patch Panel Cat 6", unitCost: 0 },
  { id: "ITM-050", description: "Pipe 1 & 1/2\"", unitCost: 40 },
  { id: "ITM-051", description: "Pipe 1&1/4\"", unitCost: 32 },
  { id: "ITM-052", description: "Polly pipe (roll) - 1/2\"", unitCost: 48 },
  { id: "ITM-053", description: "Poll pipe (roll) - 3/4\"", unitCost: 53 },
  { id: "ITM-054", description: "Patch Cord SC/APC-SC/PC 1m Single Mode", unitCost: 3 },
  { id: "ITM-055", description: "Patch Cord SC/APC-SC/PC 3m Single Mode", unitCost: 3 },
  { id: "ITM-056", description: "Patch Cord SC/PC-LC/PC 1m Single Mode", unitCost: 3 },
  { id: "ITM-057", description: "Patch Cord SC/PC-LC/PC 3m Single Mode", unitCost: 3 },
  { id: "ITM-058", description: "ROCKET M2 ( UBIQUITY )", unitCost: 118 },
  { id: "ITM-059", description: "SECTOR WIFI ANTENNA", unitCost: 252 },
  { id: "ITM-060", description: "Trunking 1&1/2\" (38*25mm)", unitCost: 2 },
  { id: "ITM-061", description: "Trunking 100X50 mm", unitCost: 13 },
  { id: "ITM-062", description: "TRUNKING 50*50", unitCost: 12 },
  { id: "ITM-063", description: "Trunking 0.5", unitCost: 3 },
  { id: "ITM-064", description: "Unifi AP Ac Pro", unitCost: 279 },
  { id: "ITM-065", description: "UNIFI LONG RANGE/ INDOOR", unitCost: 173 },
  { id: "ITM-066", description: "UNIFI long range U6", unitCost: 259 },
  { id: "ITM-067", description: "UNIFI MESH - UAP AC M", unitCost: 146 },
  { id: "ITM-068", description: "Unifi POE Switch 16 ports", unitCost: 430 },
  { id: "ITM-069", description: "Unifi POE Switch 24 ports", unitCost: 538 },
  { id: "ITM-070", description: "Unifi POE Switch 8 ports", unitCost: 0 },
  { id: "ITM-071", description: "BDCOM POE 8port Switch", unitCost: 106 },
  { id: "ITM-072", description: "Unifi SFP module", unitCost: 0 },
  { id: "ITM-073", description: "UNIFI SHORT RANGE / IN DOOR", unitCost: 0 },
  { id: "ITM-074", description: "UTP Cable CAT6 (Roll)", unitCost: 167 },
  { id: "ITM-075", description: "Water Proof box 300*250*120", unitCost: 24 },
  { id: "ITM-076", description: "Water proof box 400*350*120", unitCost: 32 },
  { id: "ITM-077", description: "EAP225-Outdoor-Tp Link", unitCost: 129 },
  { id: "ITM-078", description: "Deco M5 Tp Link", unitCost: 201 },
  { id: "ITM-079", description: "EAP 110 - Outdoor Tp Link", unitCost: 41 },
  { id: "ITM-080", description: "EAP115 Tp Link", unitCost: 49 },
  { id: "ITM-081", description: "EAP 235-Wall Tp Link", unitCost: 102 },
  { id: "ITM-082", description: "TP Link CPE610 Pair (P2P P2M)", unitCost: 46 },
  { id: "ITM-083", description: "TP Link Archer C6 AC1200 Wireless router", unitCost: 61 },
  { id: "ITM-084", description: "Mikrotik-RB951UI-2HND", unitCost: 106 },
  { id: "ITM-085", description: "Mirkotik-L009UIGS", unitCost: 259 },
  { id: "ITM-086", description: "RG EW1200", unitCost: 30 },
  { id: "ITM-087", description: "RG RAP62- OD", unitCost: 175 },
  { id: "ITM-088", description: "RG-RAP52-OD", unitCost: 94 },
  { id: "ITM-089", description: "RG-ES106F-P", unitCost: 45 },
  { id: "ITM-090", description: "RG-ES110GS-P-L", unitCost: 153 },
  { id: "ITM-091", description: "RG-ES118FGS-LP", unitCost: 207 },
  { id: "ITM-092", description: "RG-ES08G-L", unitCost: 31 },
  { id: "ITM-093", description: "RG-ES116G-L", unitCost: 103 },
  { id: "ITM-094", description: "REYEE RG -RAP6202", unitCost: 148 },
  { id: "ITM-095", description: "REYEE RG-RAP6262 (G)", unitCost: 193 },
  { id: "ITM-096", description: "REYEE RG-RAP2266", unitCost: 133 },
];

export const defaultPricing = {
  usdToTzsRate: 2500,
  items: engineerStockItems.map(({ id, description, unitCost }) => ({ id, description, unitCostUsd: unitCost })),
};

export const serviceTypes = [
  ["new_installation", "New Installation"],
  ["reconnection", "Reconnection"],
  ["wifi_extension", "WiFi Extension"],
  ["tt", "TT"],
  ["shifting_connection", "Shifting Connection"],
  ["general_maintenance", "General Maintenance"],
];

export const requestedServices = [
  "Dedicated Internet",
  "Broadband Internet",
  "Fibre Internet",
  "WiFi Installation",
  "Network Installation",
  "Link Maintenance",
];

export const subscriptionPackages = [
  "Home 10 Mbps",
  "Home 20 Mbps",
  "Business 20 Mbps",
  "Business 50 Mbps",
  "Business 100 Mbps",
  "Dedicated 10 Mbps",
  "Dedicated 20 Mbps",
  "Dedicated 50 Mbps",
  "Dedicated 100 Mbps",
];

export const currencies = ["TZS", "USD"];

export const locationOptions = [
  { name: "Mkunazini", area: "Stone Town" },
  { name: "Darajani", area: "Stone Town" },
  { name: "Kiponda", area: "Stone Town" },
  { name: "Malindi", area: "Stone Town" },
  { name: "Forodhani", area: "Stone Town" },
  { name: "Shangani", area: "Stone Town" },
  { name: "Vuga", area: "Stone Town" },
  { name: "Mchangani", area: "Stone Town" },
  { name: "Mlandege", area: "Zanzibar City" },
  { name: "Michenzani", area: "Zanzibar City" },
  { name: "Kikwajuni", area: "Zanzibar City" },
  { name: "Kilimani", area: "Zanzibar City" },
  { name: "Amani", area: "Zanzibar City" },
  { name: "Kwa Mchina", area: "Zanzibar City" },
  { name: "Mwanakwerekwe", area: "Zanzibar City" },
  { name: "Magomeni", area: "Zanzibar City" },
  { name: "Kisauni", area: "Zanzibar West" },
  { name: "Mbweni", area: "Zanzibar West" },
  { name: "Chukwani", area: "Zanzibar West" },
  { name: "Mazizini", area: "Zanzibar West" },
  { name: "Kiembesamaki", area: "Zanzibar West" },
  { name: "Fuoni", area: "Zanzibar West" },
  { name: "Bububu", area: "Zanzibar West" },
  { name: "Mtoni", area: "Zanzibar West" },
  { name: "Chuini", area: "Zanzibar West" },
  { name: "Kiembe Samaki Airport", area: "Airport" },
  { name: "Abeid Amani Karume International Airport", area: "Airport" },
  { name: "Nungwi", area: "North Zanzibar" },
  { name: "Kendwa", area: "North Zanzibar" },
  { name: "Kiwengwa", area: "North-East Zanzibar" },
  { name: "Matemwe", area: "North-East Zanzibar" },
  { name: "Paje", area: "South-East Zanzibar" },
  { name: "Jambiani", area: "South-East Zanzibar" },
  { name: "Bwejuu", area: "South-East Zanzibar" },
  { name: "Makunduchi", area: "South Zanzibar" },
  { name: "Kizimkazi", area: "South Zanzibar" },
  { name: "Fumba", area: "South-West Zanzibar" },
];
